services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: cr.yandex/<registry_id>/app:latest
    container_name: web-app
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
#    depends_on:
#      - db

#  db:
#    image: mysql:8
#    container_name: mysql-db
#    restart: always
#    networks:
#      backend:
#        ipv4_address: 172.20.0.10
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}