[webservers]
netology-develop-web-1 ansible_host= fqdn=netology-develop-web-1.ru-central1.internal
netology-develop-web-2 ansible_host= fqdn=netology-develop-web-2.ru-central1.internal

[databases]
netology-develop-db-main ansible_host= fqdn=netology-develop-db-main.ru-central1.internal
netology-develop-db-replica ansible_host= fqdn=netology-develop-db-replica.ru-central1.internal

[storage]
netology-develop-storage ansible_host= fqdn=netology-develop-storage.ru-central1.internal
